import type { ClothingCategory, Outfit, WardrobeItem } from "@/lib/types";

export const MOCK_WARDROBE: WardrobeItem[] = [
  {
    id: "shirt-ivory-001",
    name: "The linen shirt",
    category: "Tops",
    subcategory: "Button-up shirt",
    color: "Ivory",
    pattern: "Solid",
    material: "Linen",
    season: ["Spring", "Summer"],
    formality: "Smart casual",
    occasions: ["Work", "Weekend", "Dinner"],
    brand: "Studio Edit",
    notes: "A relaxed staple that works tucked or open over a tee.",
    image: "/images/item-linen-shirt.jpg",
    favorite: true,
    addedAt: "Added 2 days ago",
  },
  {
    id: "trouser-olive-002",
    name: "Olive tailored trousers",
    category: "Bottoms",
    subcategory: "Straight-leg trousers",
    color: "Deep olive",
    pattern: "Solid",
    material: "Cotton blend",
    season: ["All season"],
    formality: "Smart casual",
    occasions: ["Work", "Dinner"],
    image: "/images/item-olive-trousers.jpg",
    favorite: false,
    addedAt: "Added 4 days ago",
  },
  {
    id: "loafers-brown-003",
    name: "Leather loafers",
    category: "Shoes",
    subcategory: "Loafers",
    color: "Chestnut",
    pattern: "Solid",
    material: "Leather",
    season: ["All season"],
    formality: "Smart casual",
    occasions: ["Work", "Dinner"],
    image: "/images/item-leather-loafers.jpg",
    favorite: true,
    addedAt: "Added last week",
  },
  {
    id: "coat-sand-004",
    name: "The everyday trench",
    category: "Outerwear",
    subcategory: "Trench coat",
    color: "Sand",
    pattern: "Solid",
    material: "Cotton gabardine",
    season: ["Spring", "Autumn"],
    formality: "Smart casual",
    occasions: ["Work", "Weekend", "Travel"],
    image: "/images/item-trench-coat.jpg",
    favorite: false,
    addedAt: "Added last week",
  },
  {
    id: "knit-charcoal-005",
    name: "Soft knit tee",
    category: "Tops",
    subcategory: "Knit top",
    color: "Charcoal",
    pattern: "Solid",
    material: "Cotton knit",
    season: ["Autumn", "Winter", "Spring"],
    formality: "Casual",
    occasions: ["Weekend", "Dinner"],
    image: "/images/item-knit-top.jpg",
    favorite: false,
    addedAt: "Added 2 weeks ago",
  },
  {
    id: "denim-indigo-006",
    name: "Straight-leg denim",
    category: "Bottoms",
    subcategory: "Jeans",
    color: "Indigo",
    pattern: "Solid",
    material: "Denim",
    season: ["All season"],
    formality: "Casual",
    occasions: ["Weekend", "Travel"],
    image: "/images/item-denim-jeans.jpg",
    favorite: true,
    addedAt: "Added 2 weeks ago",
  },
  {
    id: "tote-cognac-007",
    name: "Everyday leather tote",
    category: "Accessories",
    subcategory: "Tote bag",
    color: "Cognac",
    pattern: "Solid",
    material: "Leather",
    season: ["All season"],
    formality: "Smart casual",
    occasions: ["Work", "Weekend", "Travel"],
    image: "/images/item-leather-tote.jpg",
    favorite: false,
    addedAt: "Added 3 weeks ago",
  },
  {
    id: "sneakers-cream-008",
    name: "Clean canvas sneakers",
    category: "Shoes",
    subcategory: "Low-top sneakers",
    color: "Off-white",
    pattern: "Solid",
    material: "Leather and canvas",
    season: ["Spring", "Summer", "Autumn"],
    formality: "Casual",
    occasions: ["Weekend", "Travel"],
    image: "/images/item-canvas-sneakers.jpg",
    favorite: false,
    addedAt: "Added 3 weeks ago",
  },
];

export const MOCK_OUTFITS: Outfit[] = [
  {
    id: "look-business",
    name: "Softly polished",
    occasion: "Business meeting",
    style: "Smart casual",
    reason: "Clean lines and warm neutrals feel considered without feeling overdone.",
    itemIds: ["shirt-ivory-001", "trouser-olive-002", "loafers-brown-003"],
    image: "/images/mock-outfit-editorial.jpg",
    updatedLabel: "A wardrobe favorite",
  },
  {
    id: "look-weekend",
    name: "Weekend, well spent",
    occasion: "A slow Saturday",
    style: "Relaxed minimal",
    reason: "An easy layer, familiar denim, and comfortable pieces you already reach for.",
    itemIds: ["coat-sand-004", "knit-charcoal-005", "denim-indigo-006", "sneakers-cream-008", "tote-cognac-007"],
    image: "/images/mock-outfit-weekend.jpg",
    updatedLabel: "Saved last Sunday",
  },
  {
    id: "look-after-hours",
    name: "Dinner, no overthinking",
    occasion: "Dinner out",
    style: "Elevated casual",
    reason: "A soft knit and tailored trousers make the transition from day to evening feel effortless.",
    itemIds: ["knit-charcoal-005", "trouser-olive-002", "loafers-brown-003"],
    image: "/images/mock-outfit-editorial.jpg",
    updatedLabel: "Created for you",
  },
];

export const INITIAL_SAVED_OUTFIT_IDS = ["look-business", "look-weekend"];
export const INITIAL_FAVORITE_OUTFIT_IDS = ["look-weekend"];

export const CATEGORIES: Array<"All" | ClothingCategory> = [
  "All",
  "Tops",
  "Bottoms",
  "Shoes",
  "Outerwear",
  "Accessories",
];

export const CATEGORY_IMAGE: Record<ClothingCategory, string> = {
  Tops: "/images/item-linen-shirt.jpg",
  Bottoms: "/images/item-olive-trousers.jpg",
  Shoes: "/images/item-leather-loafers.jpg",
  Outerwear: "/images/item-trench-coat.jpg",
  Accessories: "/images/item-leather-tote.jpg",
};

export const STARTER_PROMPTS = [
  "Business meeting",
  "Casual weekend",
  "Dinner tonight",
  "What goes with my linen shirt?",
];
